# Generated by Django 3.1.1 on 2020-10-13 22:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='WorkforceModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author', models.EmailField(max_length=254)),
                ('description', models.TextField()),
                ('model_name', models.CharField(max_length=256)),
                ('model_type', models.CharField(choices=[('ideal_staffing', 'Ideal Staffing'), ('ideal_staffing_current', 'Ideal Staffing Current'), ('service_allocation', 'Service Allocation')], max_length=22)),
                ('start_year', models.IntegerField()),
                ('end_year', models.IntegerField()),
                ('step_size', models.IntegerField()),
                ('removed_professions', models.JSONField()),
                ('path', models.CharField(max_length=512)),
                ('filename', models.CharField(max_length=512)),
                ('status', models.CharField(choices=[('Failed', 'Failed'), ('Running', 'Running'), ('Completed', 'Completed')], max_length=9)),
            ],
        ),
    ]
