# Generated by Django 3.1.1 on 2020-10-21 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workforceAPI', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='workforcemodel',
            name='is_public',
            field=models.BooleanField(default=False),
        ),
    ]
